name: Run Unit Tests

on:
  push:
    branches: [ main, ddl-operation ]
  pull_request:
    branches: [ main, ddl-operation ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345678
          POSTGRES_DB: database_services_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Set DATABASE_URL
        run: echo "DATABASE_URL=postgres://postgres:12345678@localhost:5432/database_services_test" >> $GITHUB_ENV

      - name: Wait for Postgres to be ready
        run: |
          for i in {1..10}; do
            echo "Checking PostgreSQL connection..."
            pg_isready -h localhost -p 5432 && exit 0
            echo "PostgreSQL not ready, retrying in 5s..."
            sleep 5
          done
          echo "PostgreSQL failed to start!" && exit 1

      - name: Debug DATABASE_URL
        run: echo $DATABASE_URL

      - name: Check Database Connection
        run: |
          PGPASSWORD=12345678 psql -h localhost -U postgres -d database_services_test -c "\dt"

      
      - name: Check PostgreSQL logs
        run: docker logs $(docker ps -q --filter "ancestor=postgres:13")


      - name: Wait for database to settle
        run: sleep 10

      - name: Sync Database
        env:
          NODE_ENV: test
          DB_USERNAME: postgres
          DB_PASSWORD: 12345678
          DB_NAME: database_services_test
          DB_HOST: localhost
          JWT_SECRET: supersecretkey
          JWT_EXPIRES_IN: 1h
        run: yarn sync-db

      - name: Run migrations
        env:
          DB_USERNAME: postgres
          DB_PASSWORD: 12345678
          DB_NAME: database_services_test
          DB_HOST: localhost
          JWT_SECRET: supersecretkey
          JWT_EXPIRES_IN: 1h
        run: yarn migrate

      - name: Run tests
        env:
          NODE_ENV: test
          DB_USERNAME: postgres
          DB_PASSWORD: 12345678
          DB_NAME: database_services_test
          DB_HOST: localhost
          JWT_SECRET: supersecretkey
          JWT_EXPIRES_IN: 1h
        run: yarn test
